name: Android Release

# 1
on:
  # 2
  push:
    tags:
    - '*'
  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest
    permissions: write-all

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.16.3"
          channel: 'stable'
          cache: true

      # - name: Decode android/neumodore_key.jks
      #   run: echo "${{ secrets.KEYSTORE_JKS_PROD }}" | base64 --decode > android/keystore.jks

      # - name: Decode android/key.properties
      #   run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties

      # - name: Replace YAML version with tag version
      #   run: |
      #     sed -i 's/99.99.99+99/'$GIT_TAG_NAME'/g' pubspec.yaml|
      #     echo "Tag used version:"$GIT_TAG_NAME
      #
      - id: get_version
        name: Get Version
        uses: jannemattila/get-version-from-tag@v1

      - name: Pub Get Packages
        run: "flutter pub get"

      - name: Build APPBUNDLE
        run: "flutter build appbundle --build-name=${{ steps.get_version.outputs.version }}"

      - name: Build APK
        run: "flutter build apk --split-per-abi --build-name=${{ github.ref_name }}"

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*.aab,build/app/outputs/flutter-apk/*.apk"
          # tag: $GIT_TAG_NAME
          # token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}

     
   
